### ISSUE TITLE
Not really a single aggregated entry per language

### ISSUE THREAD

**Issue by murawaki** [autotyp/autotyp-data#11]
A possible bug in aggregation. Module VInfl_macrocat_multiexponence is of type 'single aggregated entry per language'. However, LID 382, among many others, appears in two rows (Lines 91 and 92).

**Comment by tzakharko** [comment]
This should be fixed in 1.0.0. Apologies for taking so long, we were busy rebuilding the data export and aggregation pipeline from scratch.
