### ISSUE TITLE
Match LID to Glottocode or ISO-639

### ISSUE THREAD

**Issue by Khildeb1** [autotyp/autotyp-data#13]
How can I match the LID's to the glottocodes or ISO's in the various data files?

**Comment by agricolamz** [comment]
I can find only the weird answer in [this file](https://github.com/autotyp/autotyp-data/blob/98cae32c387bfe0c7fb1b7151070d834b120a0f1/metadata/Register.yaml), but I've created [such a file](https://github.com/ropensci/lingtypology/blob/master/database_creation/autotyp.RData) for lingtypology package. I'm not an owner, so probably Taras or somebody else will answer you, if you'll reopen the issue.

**Comment by tzakharko** [comment]
This report was closed but for the sake of completeness: Register.csv offers ISO639.3 and Glottocode columns for this.
