### ISSUE TITLE
Datatype "logical" is not explained in the docs

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#24]
In the list of possible datatypes at https://github.com/autotyp/autotyp-data#data-types-in-variables-fields `logical` is missing. This appears, e.g. here:
https://github.com/autotyp/autotyp-data/blob/88133f01232702659bac179baafbb99d3adc1727/metadata/Register.yaml#L196-L202

**Comment by tzakharko** [comment]
Ah, good catch, that is an oversight. Will update the readme, unfortunately the release is already out. Will be fixed in a minor update.
