### ISSUE TITLE
Unspecified value FloatingorClitic in Morphology->LocusOfMarkingPerMicrorelation->LocusOfMarkingBinned5

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#27]
The list of values for `LocusOfMarkingBinned5` doesn't include `FloatingorClitic`:
https://github.com/autotyp/autotyp-data/blob/88133f01232702659bac179baafbb99d3adc1727/metadata/Morphology/LocusOfMarkingPerMicrorelation.yaml#L345-L362
but the data does:
```shell
$ grep FloatingorClitic raw/autotyp-data/data/json/Morphology/LocusOfMarkingPerMicrorelation.json -m 1
        "LocusOfMarkingBinned5": "FloatingorClitic"
```

**Comment by tzakharko** [comment]
Thank you for the report! I have created #30 to track this and related issues. Should you want to report more problems of this kind, please post them there.
