### ISSUE TITLE
Invalid value for GrammaticalMarkers->MarkerPositionBinned4

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#28]
[GrammaticalMarkers->MarkerPositionBinned4](https://github.com/autotyp/autotyp-data/blob/88133f01232702659bac179baafbb99d3adc1727/metadata/Morphology/GrammaticalMarkers.yaml#L680) does not list `in/simul` as valid value, but it occurs in the data:
```shell
$ grep "in/simul" raw/autotyp-data/data/json/Morphology/GrammaticalMarkers.json -m 1
    "MarkerPositionBinned4": "in/simul",
```

**Comment by tzakharko** [comment]
Thank you for the report! I have created #30 to track this and related issues. Should you want to report more problems of this kind, please post them there.
