### ISSUE TITLE
Duplicate records

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#33]
I found 67 records to have duplicates - i.e. multiple identical records in the same dataset. Most are in `Categories`, in datasets that do not otherwise have multiple records for the same language - so I guess these should just be removed. 20 are in WordDomains. Whether identical duplicates are meaningful there - where other languages have multiple - different - records, I don't know.

**Comment by tzakharko** [comment]
Duplicate database entries have been removed from `Alienability`, `Gender` and `NumeralClassifiers` in 8ef34905f40d63dc3898c8652444b25722d403fd. Duplicates in `WordDomain` are a known defect — we are working on an overhaul of that dataset.
