### ISSUE TITLE
Subsistence types in nene1249

### ISSUE THREAD

**Issue by bambooforest** [autotyp/autotyp-data#4]
Perhaps not an issue, but I thought I'd submit it just in case.

Nenets (Forest) nene1249 (yrk)
Nenets (Tundra) nene1249 (yrk)

have different AUTOTYP IDs (but the same Glottolog code and ISO code). These data points indicate two different subsistence types: agricultural/pastoral and hunting/fishing/foraging

The rows:

https://github.com/autotyp/autotyp-data/blob/master/data/Register.csv#L55
https://github.com/autotyp/autotyp-data/blob/master/data/Register.csv#L553

**Comment by balthasarbickel** [comment]
Fixed in our database. Will appear in the next incremental release.
