### ISSUE TITLE
Multiple geographic locations

### ISSUE THREAD

**Issue by bambooforest** [autotyp/autotyp-data#5]
Some data points in the Register have multiple geographic locations:

indo1316 -- Eurasia vs Pacific (Indonesian)
oira1263 -- Pacific vs Eurasia (Oirata; Indonesia)

which seem ok, but these two seem weird:

kyer1238 -- Eurasia vs Africa (Kyerung; Nepal)
kati1270 -- Eurasia vs Pacific (Afghanistan / Pakistan)

Perhaps wrong Glottolog code assignment?

**Comment by tzakharko** [comment]
Fixed in the database, will be exported with the next incremental release.

**Comment by HedvigS** [comment]
I found some more, in register.csv the following languoids have more than one Area associated with them: 
‘balk1252’, ‘east2295’, ‘indo1316’, ‘kati1270’, ‘kyer1238’, ‘mart1256’, ‘minn1241’, ‘noga1249’, ‘oira1263’, ‘peri1253’, ‘taha1241’, ‘tibe1272’, ‘till1254’, ‘toho1245’

Sometimes the long/lat are also widely different, as in 'kati1270'.

glottocode|Area|longitude|latitude
-- | -- | -- | --
kati1270 | Indic | 70.00 | 35.50
 kati1270 | S New Guinea | 140.92 | -5.75

**Comment by balthasarbickel** [comment]
Thanks!

Balthasar.
