### ISSUE TITLE
Equivalent states treated as different in Alignment

### ISSUE THREAD

**Issue by nataliacp** [autotyp/autotyp-data#53]
In alignment variable DominantAlignmentPTGForCase, there are states
1 P=T=G
2 P=T≠G
3 mixed
4 T≠P≠G
5 T≠P=G
6 G≠P=T
7 P=G≠T
8 ?
states 2 and 6 are the same and states 5 and 7 are the same.

**Comment by tzakharko** [comment]
Thank you for the bug report! This is now fixed in a8f294f4810ed882ae6dbffa4e5490e3bafa041e

You can use the dataset from GitHub until this becomes part of an official Zenodo release
