### ISSUE TITLE
Some glottolog codes

### ISSUE THREAD

**Issue by agricolamz** [autotyp/autotyp-data#6]
Dear Taras, 

* glottolog code for Gurung [in Register.csv](https://raw.githubusercontent.com/autotyp/autotyp-data/master/data/Register.csv) could be [`guru1261`](http://glottolog.org/resource/languoid/id/guru1261) (now it is [`west2414`](http://glottolog.org/resource/languoid/id/west2414))
* glottolog code for Ashéninka Perené (LID 3240) could be [`ashe1272`](http://glottolog.org/resource/languoid/id/ashe1272) (now there is no any)

**Comment by tzakharko** [comment]
We checked the glottocodes and fixed Ashéninka Perené, Gurung in our sample refers to Western Gurung and so west2414 is indeed correct. 

P.S. Sorry for taking so long with this, the export and aggregation pipeline had to undergo significant redesign. With the new tech stack we are able to provide updates much faster and with more precision than before.
